//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfGym_Servidor
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EJERCICIO
    {    
        [Key]
        public int EJE_ID { get; set; }
        public string EJE_CODIGO { get; set; }
        public string EJE_NOMBRE { get; set; }
        public string EJE_LINKTUTORIAL { get; set; }
    }
}
