//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfGym_Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EJERCICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EJERCICIO()
        {
            this.RUTINA_EJERCICIO = new HashSet<RUTINA_EJERCICIO>();
        }
    
        public int EJE_ID { get; set; }
        public string EJE_CODIGO { get; set; }
        public string EJE_NOMBRE { get; set; }
        public string EJE_LINKTUTORIAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RUTINA_EJERCICIO> RUTINA_EJERCICIO { get; set; }
    }
}
