//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfGym_Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_RUTINA
    {
        public int USU_RUT_ID { get; set; }
        public string USU_NOMBREUSUARIO { get; set; }
        public Nullable<int> RUT_ID { get; set; }
    
        public virtual RUTINA RUTINA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
