//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfGym_Backend
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class CATEGORIA
    {
        public string CAT_ID { get; set; }
        public string CAT_NOMBRE { get; set; }
        public string CAT_DESCRIPCION { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIA()
        {
            this.EJERCICIO = new HashSet<EJERCICIO>();
        }

        [XmlIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EJERCICIO> EJERCICIO { get; set; }
    }
}
