//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfGym_Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIA
    {
        public string NOT_ID { get; set; }
        public string NOT_DESCRIPCION { get; set; }
    }
}
